### ISSUE TITLE
Studio is broken since latest commit

### ISSUE THREAD

**Issue by Asduffo** [Joey35233/FMDL-Studio-v2#12]
The studio just stopped working since the latest commit. 
At first I thought it was an issue with PT models but then I found out that neither MGSV models such as the famous sna2_main0_def.fmdl works.
The last working commit I found is the one by bob named "Fixed bounding box size issue. Root bone is now created." for which i developed a cool feature to finally save the models persistently into the assets folder.

The issue is on row 1069:
`            reader.BaseStream.Position = section0BlockEEntries[2].offset + section1Offset + section1Info[faceIndicesIndex].offset + section0Block11Entries[i].firstFaceVertexId;`

and the issue states

IndexOutOfRangeException: Index was outside the bounds of the array.
Fmdl.Read (System.IO.FileStream stream) (at Assets/Scripts/Data/Fmdl.cs:1069)
FmdlImporter.FMDLStream (System.String path, System.Boolean shouldSave) (at Assets/Editor/FmdlImporter.cs:11)
FmdlWindow.LoadFMDL () (at Assets/Editor/FmdlWindow.cs:9)

**Comment by Joey35233** [comment]
Check out Bob's commit.

**Comment by Asduffo** [comment]
Yeah fixed. BTW i suggest you to check out the new fbx tools which unity provides in version 2017.2
