### ISSUE TITLE
Is the FBX exported with a left hand system or right handed?

### ISSUE THREAD

**Issue by Asduffo** [Joey35233/FMDL-Studio-v2#15]
Not a real issue, but just a quick question: when the fbx is exported, is it exported with a left-handed coordinates system (used by unity) or right handed (used by blender and 3DS max)? Cause last time I was trying to attach an animation done with id-daemon's tools with a model I exported with your tool and the result was quite funny 
![cattura](https://user-images.githubusercontent.com/10978638/32493556-8c47d6bc-c3be-11e7-9910-cbae3eb15141.PNG)

The bones are located correctly (here they are facing the camera) but it always rotates the model to the right. This usually suggests that the animation and the model are using different hand system. Since the animation was made with blender, ergo right hand, my poor experience with modelling suggests that the fbx had been exported with a left hand system in mind. Is that the case? And if that's so, what should be changed to make it export right-handed?

**Comment by devilsnake88** [comment]
I'm not good with this kind of things but can it have something to do with IK constraints?
Also, do you have Discord or Steam?

**Comment by Asduffo** [comment]
Hi. "something to do with IK constraints" is a bit generic ^_^' what do you want me exactly to try? Anyway I do have Steam, why?

**Comment by BobDoleOwndU** [comment]
id-daemon's animation tool requires IK constraints to be set up manually.

> After unpacking, load the model and apply it. 
Then connect arms to palms and legs to feet with IK constraints.

>Example: connect IK_LARM -----> SKL_013_LHAND, and use pole vector IK_POLEARM_L
You will also need to do something with twist bones, this is not done automatically yet.

I don't know how exactly these are set up or if that's the only compatibility issue between the tool and models output by Fmdl Studio v2; but they're needed for animations to work.

**Comment by Asduffo** [comment]
Yeah I know exactly how to setup IKs from daemon's tool (and judging by how animations behaves, I can't see anythin wrong with them), the question was what did you wanted me to try with them.

Anyway if what you meant was simply trying to delete/unlink the IKs, it still gives me the same result: the model is rotated 90 degrees right before attaching the animation when I import it.

**Comment by BobDoleOwndU** [comment]
Ah. The issue probably is Unity's left-handed coordinate system then. In order for the models to not be mirrored, the x and z coordinates read from the model data had to be flipped. This also causes the models to appear facing left rather than the front, which may be the cause of the problem.

**Comment by Asduffo** [comment]
mh ok. Is there a quick way to fix it (like swapping some parameter on the fbx exporter) that a noob in fbx like me can do or does it require higher level stuff?

**Comment by BobDoleOwndU** [comment]
Just rotating the model 90 degrees in the modelling program might work. I'm not sure though.

**Comment by Asduffo** [comment]
Already tried rotating in 100 ways in both unity and 3ds max and blender (both model and animation). It's no use and it will always end up rotating 90 degrees right (on 3ds max it's always facing "left")

**Comment by Joey35233** [comment]
Did you make sure to rotate the skeleton, not the mesh, and reset the bind
pose to that new position?

**Comment by Asduffo** [comment]
If you mean rotating the animation itself before exporting yes as I already said I tried in every single rotation possible.

If you meant to apply the rotation to IKLARM etc to the ik poles (that "You will also need to do something with twist bones, this is not done automatically yet") of course I did it otherwise the animation itself wouldn't animate properly.

The mtar tool already instances the animation into the bind pose so when imported it already works fine.

If for "rotate the skeleton, not the mesh, and reset the bind pose to that new position" you meant rotating the skeleton generated by fmdl studio while on 3ds max and then make a copy of the meshes and then copy the skin modifiers to the new ones yeah I tried that too but once I paste the skin modifier to the copied meshes self-rotates wrongly again. 

If you meant something else just tell me. Again I'm kinda of a noob with modelling tools ^_^"

**Comment by Joey35233** [comment]
Rotate the skeleton, right click on the mesh and choose "set new bind pose".

**Comment by Asduffo** [comment]
If you meant "set as skin pose" from the animations menu, tried and nothin changes. I never heard of a command called "set new bind pose". If I right click on a mesh I can't see such an option and to be double sure I googled it and I couldn't find anything. Are you talking about 3DS max or another program?

Uh also I forgot to mention that when I do import an object from fmdl studio I get this warning:
_The Initial position (or Initial Pose) of the skinned objects is missing. 
The plug-in will create a pose automatically but running the 
'Assume Skin Pose' command may create unexpected results._

**Comment by Joey35233** [comment]
Hey, sorry for the silence on this issue? Do you think it would be too much to ask for you to get a Discord account? We have a Discord where we develop the tool and work on other projects as well; it would be easier to troubleshoot this issue there.

**Comment by devilsnake88** [comment]
Hey guys,
I have talk with ID-Daemon and he tested his tool into Blender and he told me there is no issues with the models I sent him (using your FMDL Studio V2).
This is why he made his last video right here: https://www.youtube.com/watch?v=uWgoNnJpFv8
Plus, he will make a tutorial on how to use his tool soon so wait and see :)

**Comment by Asduffo** [comment]
Hi sorry for the delay but sometimes internet blows up in my campus. Anyway will wait a little more for this so much anticipated ID's tutorial and then will see

**Comment by Joey35233** [comment]
ID's tutorial will be for the cutscene animations. The animations you are
looking at are the gameplay animations, which are very different.
