### ISSUE TITLE
Package imported but no "FMDL Studio" window

### ISSUE THREAD

**Issue by SnakeePlissken** [Joey35233/FMDL-Studio-v2#29]
I tried running the script Fmdlexporter.cs from the Assets/Editor but nothing happens other than a cmd window that pops on the screen for a split second, I tried to printscreen to read what it says and the message is "Cannot open assembly '(script path)': File does not contain a valid CIL image" 

I also get this on the bottom of the window as soon as I open the project in Unity: "Assets/Scripts/Data/Fmdl.cs(5,7): error CS1041: Identifier expected: `static' is a keyword"

**Comment by BobDoleOwndU** [comment]
Did you follow the instructions on the [wiki](https://github.com/BobDoleOwndU/FMDL-Studio-v2/wiki)?

**Comment by SnakeePlissken** [comment]
@BobDoleOwndU can you help me with this: The only options on configuration (Edit > Project Settings > Player) are Scripting Backend, Disable HW Statistics, and Scripting Define Symbols, both in settings for web player and settings for PC, and another thing, I forgot to mention before that I did not find a .unitypackage (although I did on the previous version, but I still had the same errors) so I just extracted all the files into my project.

**Comment by BobDoleOwndU** [comment]
If the Scripting Runtime Version option is missing, you might need to update Unity. In the Unity Editor, go to Help > Check for Updates. Let it update and the option should be there.

**Comment by SnakeePlissken** [comment]
Thanks! All working perfectly, and thank you for this project!
