### ISSUE TITLE
fmdl.GetSection0Block16Entries()[fmdl.GetSection0Block0Entries()[i].nameId]) is always null and throws NullReferenceException

### ISSUE THREAD

**Issue by Asduffo** [Joey35233/FMDL-Studio-v2#6]
On row 58,
`bones[i] = new GameObject(Hashing.TryGetName(fmdl.GetSection0Block16Entries()[fmdl.GetSection0Block0Entries()[i].nameId])).transform;`

You're using fmdl.`GetSection0Block16Entries(...)` to name a transform. However, it always return a `null ` result, so it's impossible to continue the job and the model won't be imported. `fmdl.GetSection0Block0Entries()[i].nameId` itself works fine, is GetSection0Block16Entries who is `null `no matter which adress uses.

The issue started after the release who named the bones. Before it worked fine even with Silent Hills PT objects.

**Comment by BobDoleOwndU** [comment]
The tool is currently based on the TPP format. PT models use the GZ format, which lack the hash list, which is what's causing the error. The GZ format is planned to be supported; but it's not our biggest priority for the time being.

**Comment by Asduffo** [comment]
Then how it comes it was working flawlessy with every model till the release which named the bones?

**Comment by Joey35233** [comment]
Because until then it didn't need to reference block 0x16 in any way.

**Comment by Joey35233** [comment]
Sorry 0x16 is the hashed name list. Nothing needed names up until that
point, and so there were never any issues.

**Comment by Joey35233** [comment]
Bob added support for GZ Hashes.

**Comment by Asduffo** [comment]
Wow a m a z i n g!!!
